- name: sedentary_break
  topic_id: movement
  priority: 40
  cooldown_seconds: 1800
  max_per_day: 6
  condition:
    cond:
      gte: [ "signal:sedentary_minutes", 120 ]
    severity:
      between: [ "signal:sedentary_minutes", 90, 240 ]
    bindings:
      sitting_minutes: "signal:sedentary_minutes"
  tone_strategy:
    map:
      - gte: [ "severity", 0.7 ]
        tone: firm
      - gte: [ "severity", 0.4 ]
        tone: persistent
    default: gentle
  context_template: "sitting_minutes={{sitting_minutes}}"

- name: hydration_gap
  topic_id: hydration
  priority: 50
  cooldown_seconds: 3600
  max_per_day: 6
  condition:
    cond:
      gte: [ "signal:minutes_since_water", 120 ]
    severity:
      between: [ "signal:minutes_since_water", 90, 240 ]
    bindings:
      gap: "signal:minutes_since_water"
  tone_strategy:
    map:
      - gte: [ "severity", 0.7 ]
        tone: firm
      - gte: [ "severity", 0.4 ]
        tone: persistent
    default: gentle
  context_template: "gap={{gap}}"
